apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: self-signed
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: cert@penxle.io
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - dns01:
          route53: {}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: cert@penxle.io
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - dns01:
          route53: {}
