apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-dns-cloudflare
  namespace: kube-system
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: ssm
    kind: ClusterSecretStore
  target:
    name: external-dns-cloudflare
  data:
    - secretKey: CF_API_TOKEN
      remoteRef:
        key: /cloudflare/external_dns/api_token
