apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: meilisearch-master-key
  namespace: dev
spec:
  refreshInterval: 0s
  target:
    name: meilisearch-master-key
    creationPolicy: Owner
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ClusterGenerator
          name: password
      rewrite:
        - regexp:
            source: ".*"
            target: "MEILI_MASTER_KEY"
