apiVersion: cilium.io/v2
kind: CiliumEnvoyConfig
metadata:
  name: api-l7-proxy
  labels:
    cilium.io/use-original-source-address: "false"
spec:
  services:
    - name: api
      namespace: dev
  backendServices:
    - name: api
      namespace: dev
  resources:
    - "@type": type.googleapis.com/envoy.config.listener.v3.Listener
      name: api-l7-proxy
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: api-l7-proxy
                upgrade_configs:
                  - upgrade_type: websocket
                rds:
                  route_config_name: api-l7-proxy-route
                http_filters:
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
    - "@type": type.googleapis.com/envoy.config.route.v3.RouteConfiguration
      name: api-l7-proxy-route
      virtual_hosts:
        - name: default
          domains: ["*"]
          routes:
            - match:
                prefix: "/"
              route:
                cluster: "dev/api:80"
    - "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
      name: "dev/api:80"
      connect_timeout: 5s
      lb_policy: ROUND_ROBIN
      type: EDS
      outlier_detection:
        split_external_local_origin_errors: true
        consecutive_local_origin_failure: 2
