fullnameOverride: "api"

replicas: 1

image:
  name: ghcr.io/penxle/api

resources:
  cpu: 1000m
  memory: 2Gi

env:
  - name: PUBLIC_ENVIRONMENT
    value: "dev"
  - name: NO_WORKER
    value: "true"

secrets:
  - api-aws
  - api-doppler
