apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-path-provisioner
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: system
    app.kubernetes.io/component: storage
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  sources:
    - chart: local-path-provisioner
      repoURL: https://charts.containeroo.ch
      targetRevision: 0.0.33
      helm:
        valuesObject:
          storageClass:
            create: false
            provisionerName: rancher.io/local-path

          nodePathMap:
            - node: DEFAULT_PATH_FOR_NON_LISTED_NODES
              paths:
                - /var/mnt/data

    - repoURL: https://github.com/penxle/kube
      targetRevision: HEAD
      path: system/local-path-provisioner
      directory:
        exclude: application.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
