apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
  namespace: datadog
spec:
  global:
    clusterName: k8s
    site: ap1.datadoghq.com

    credentials:
      apiSecret:
        secretName: datadog-secret
        keyName: api-key
      appSecret:
        secretName: datadog-secret
        keyName: app-key

    kubelet:
      tlsVerify: false

  features:
    processDiscovery:
      enabled: false

  override:
    nodeAgent:
      tolerations:
        - operator: Exists
