apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: datadog
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: observability
    app.kubernetes.io/component: monitoring
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  sources:
    - chart: datadog-operator
      repoURL: https://helm.datadoghq.com
      targetRevision: 2.13.1

    - repoURL: https://github.com/penxle/kube
      targetRevision: HEAD
      path: observability/datadog
      directory:
        exclude: application.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: datadog

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
