apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-credentials
  namespace: prod
spec:
  refreshInterval: 0s
  target:
    name: db-credentials
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      data:
        username: app
        password: "{{ .password }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ClusterGenerator
          name: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-aws
  namespace: prod
spec:
  refreshInterval: 0s
  secretStoreRef:
    name: ssm
    kind: ClusterSecretStore
  target:
    name: db-aws
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: /postgres/aws_access_key_id
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: /postgres/aws_secret_access_key
