apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: db
  namespace: dev
spec:
  retentionPolicy: 7d
  configuration:
    destinationPath: s3://postgres/dev
    endpointURL: https://ada355841e173023d4ac3b5a9ba71669.r2.cloudflarestorage.com
    s3Credentials:
      accessKeyId:
        name: db-cf
        key: AWS_ACCESS_KEY_ID
      secretAccessKey:
        name: db-cf
        key: AWS_SECRET_ACCESS_KEY
    data:
      compression: bzip2
    wal:
      compression: zstd
      maxParallel: 8
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: db
  namespace: dev
  annotations:
    ad.datadoghq.com/postgres.checks: |
      {
        "openmetrics": {
          "init_config": {},
          "instances": [
            {
              "openmetrics_endpoint": "http://%%host%%:9187/metrics",
              "namespace": "postgres",
              "metrics": [".*"]
            }
          ]
        }
      }
spec:
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: postgresql-standard-trixie
    major: 17

  bootstrap:
    initdb:
      walSegmentSize: 16
      secret:
        name: db-credentials

  managed:
    roles:
      - name: app
        login: true
        passwordSecret:
          name: db-credentials
      - name: root
        login: true
        superuser: true
        passwordSecret:
          name: db-credentials-root

  primaryUpdateMethod: switchover

  instances: 1
  enablePDB: false

  resources:
    requests:
      cpu: "1"
    limits:
      memory: 2Gi

  postgresql:
    parameters:
      max_connections: "100"
      wal_buffers: 4MB
      wal_keep_size: 1GB
      max_wal_size: 1GB
      min_wal_size: 80MB
      wal_writer_delay: 1000ms
      wal_writer_flush_after: 1MB
      checkpoint_timeout: 15min
      checkpoint_completion_target: "0.9"
      shared_buffers: 256MB
      effective_cache_size: 1GB
      work_mem: 4MB
      maintenance_work_mem: 64MB
      max_worker_processes: "2"
      max_parallel_workers: "2"
      max_parallel_workers_per_gather: "1"
      default_toast_compression: lz4
      track_activity_query_size: "4096"
      pg_stat_statements.track: ALL
      pg_stat_statements.max: "10000"
      pg_stat_statements.track_utility: "0"
      autovacuum_max_workers: "4"
      autovacuum_naptime: 10s
      autovacuum_vacuum_scale_factor: "0.01"
      autovacuum_analyze_scale_factor: "0.005"
      autovacuum_vacuum_cost_delay: 0ms
      autovacuum_vacuum_cost_limit: "10000"

  replicationSlots:
    highAvailability:
      enabled: true

  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          cnpg.io/cluster: db
          cnpg.io/podRole: instance

  storage:
    storageClass: local-path
    size: 10Gi

  walStorage:
    storageClass: local-path
    size: 10Gi

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: db
---
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: db-pooler
  namespace: dev
spec:
  cluster:
    name: db

  instances: 1
  type: rw

  template:
    spec:
      containers: []
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              cnpg.io/poolerName: db-pooler

  serviceTemplate:
    metadata:
      annotations:
        external-dns.typie.io/enabled: "true"
        external-dns.alpha.kubernetes.io/internal-hostname: dev.db.typie.io

  pgbouncer:
    poolMode: transaction
    parameters:
      max_client_conn: "100"
      min_pool_size: "5"
      default_pool_size: "10"
      reserve_pool_size: "10"
      server_check_delay: "10"
      server_login_retry: "0"
      idle_transaction_timeout: "300"
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: db
  namespace: dev
spec:
  schedule: "0 0 19 * * *"
  backupOwnerReference: self
  cluster:
    name: db
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: db
spec:
  cluster:
    name: db
  name: app
  owner: app
  extensions:
    - name: pgstattuple
