apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-credentials
spec:
  refreshPolicy: CreatedOnce
  target:
    name: db-credentials
    template:
      type: kubernetes.io/basic-auth
      data:
        username: app
        password: "{{ .password }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ClusterGenerator
          name: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-credentials-root
spec:
  refreshPolicy: CreatedOnce
  target:
    name: db-credentials-root
    template:
      type: kubernetes.io/basic-auth
      data:
        username: root
        password: "{{ .password }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ClusterGenerator
          name: password
