apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openebs
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: system
    app.kubernetes.io/component: storage
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  sources:
    - chart: openebs
      repoURL: https://openebs.github.io/openebs
      targetRevision: 4.3.3
      helm:
        valuesObject:
          localpv-provisioner:
            localpv:
              enabled: false
            rbac:
              create: false
            hostpathClass:
              enabled: false

          zfs-localpv:
            zfsNode:
              encrKeysDir: /var/openebs/keys
              allowedTopologyKeys: volumes.typie.io/zfs

          engines:
            local:
              lvm:
                enabled: false
              zfs:
                enabled: true
            replicated:
              mayastor:
                enabled: false

          loki:
            enabled: false

          alloy:
            enabled: false

    - repoURL: https://github.com/penxle/kube
      targetRevision: HEAD
      path: system/openebs
      directory:
        exclude: application.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
