apiVersion: generators.external-secrets.io/v1alpha1
kind: ClusterGenerator
metadata:
  name: password
spec:
  kind: Password
  generator:
    passwordSpec:
      length: 32
      symbolCharacters: "-_."
      noUpper: false
      allowRepeat: true
