apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: ssm
spec:
  provider:
    aws:
      service: ParameterStore
      region: ap-northeast-2
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: external-secrets-aws
            namespace: kube-system
            key: AWS_ACCESS_KEY_ID
          secretAccessKeySecretRef:
            name: external-secrets-aws
            namespace: kube-system
            key: AWS_SECRET_ACCESS_KEY
