apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reloader
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: system
    app.kubernetes.io/component: automation
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    chart: reloader
    repoURL: https://stakater.github.io/stakater-charts
    targetRevision: 2.2.3
    helm:
      valuesObject:
        reloader:
          isArgoRollouts: true
          reloadOnCreate: true
          syncAfterRestart: true

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
